language: php

sudo: false

php:
  - 5.6
  - 7.1

jobs:
  include:
    - dist: precise
      php: 5.3
    - dist: trusty
      php: 5.4
    - dist: trusty
      php: 5.5

matrix:
    fast_finish: true

branches:
  only:
    - master
    - 2.x

install:
  - composer install

script:
  - vendor/bin/phpunit
